version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sergey_rabbitmq_server_1
      APP_PORT: 15672
    
  server:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER=user
        RABBITMQ_DEFAULT_PASS=bNjPKaV05wJF
    #volumes:
    #    - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #    - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
