version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sergey_rabbitmq_server_1
      APP_PORT: 15672
    
  server:
    image: rabbitmq:3.10.7-management
    restart: on-failure
    user: "1000:1000"
    init: true
    ports:
      - 15672:15672
      - 5672:5672
