version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: sergey_rabbitmq_server_1
      APP_PORT: 3000
    
  server:
    image: rabbitmq:3.10.7-management
    restart: always
    user: "1000:1000"
    init: true
